//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRS.WebApi.AccountsOracleGLLoader {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadOracleGLRequest", Namespace="http://www.gulffinance.com.sa/frs/v1/accounts/oraclegl/operations/load/request")]
    [System.SerializableAttribute()]
    public partial class LoadOracleGLRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long LoadIdField;
        
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long LoadId {
            get {
                return this.LoadIdField;
            }
            set {
                if ((this.LoadIdField.Equals(value) != true)) {
                    this.LoadIdField = value;
                    this.RaisePropertyChanged("LoadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadOracleGLResponse", Namespace="http://www.gulffinance.com.sa/frs/v1/accounts/oraclegl/operations/load/response")]
    [System.SerializableAttribute()]
    public partial class LoadOracleGLResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long CodeField;
        
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gulffinance.com.sa/frs/v1/accounts/oraclegl/operations", ConfigurationName="AccountsOracleGLLoader.FrsOracleGLLoaderService")]
    public interface FrsOracleGLLoaderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gulffinance.com.sa/frs/v1/accounts/oraclegl/operations/FrsOracleGLLoad" +
            "erService/LoadOracleGL", ReplyAction="http://www.gulffinance.com.sa/frs/v1/accounts/oraclegl/operations/FrsOracleGLLoad" +
            "erService/LoadOracleGLResponse")]
        FRS.WebApi.AccountsOracleGLLoader.LoadOracleGLResponse LoadOracleGL(FRS.WebApi.AccountsOracleGLLoader.LoadOracleGLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gulffinance.com.sa/frs/v1/accounts/oraclegl/operations/FrsOracleGLLoad" +
            "erService/LoadOracleGL", ReplyAction="http://www.gulffinance.com.sa/frs/v1/accounts/oraclegl/operations/FrsOracleGLLoad" +
            "erService/LoadOracleGLResponse")]
        System.Threading.Tasks.Task<FRS.WebApi.AccountsOracleGLLoader.LoadOracleGLResponse> LoadOracleGLAsync(FRS.WebApi.AccountsOracleGLLoader.LoadOracleGLRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FrsOracleGLLoaderServiceChannel : FRS.WebApi.AccountsOracleGLLoader.FrsOracleGLLoaderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FrsOracleGLLoaderServiceClient : System.ServiceModel.ClientBase<FRS.WebApi.AccountsOracleGLLoader.FrsOracleGLLoaderService>, FRS.WebApi.AccountsOracleGLLoader.FrsOracleGLLoaderService {
        
        public FrsOracleGLLoaderServiceClient() {
        }
        
        public FrsOracleGLLoaderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FrsOracleGLLoaderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FrsOracleGLLoaderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FrsOracleGLLoaderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FRS.WebApi.AccountsOracleGLLoader.LoadOracleGLResponse LoadOracleGL(FRS.WebApi.AccountsOracleGLLoader.LoadOracleGLRequest request) {
            return base.Channel.LoadOracleGL(request);
        }
        
        public System.Threading.Tasks.Task<FRS.WebApi.AccountsOracleGLLoader.LoadOracleGLResponse> LoadOracleGLAsync(FRS.WebApi.AccountsOracleGLLoader.LoadOracleGLRequest request) {
            return base.Channel.LoadOracleGLAsync(request);
        }
    }
}
