//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRS.WebApi.FrsBankMT940Loader {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadMT940Request", Namespace="http://www.gulffinance.com.sa/frs/v1/bank/mt940/operations/load/request")]
    [System.SerializableAttribute()]
    public partial class LoadMT940Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long LoadIdField;
        
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long LoadId {
            get {
                return this.LoadIdField;
            }
            set {
                if ((this.LoadIdField.Equals(value) != true)) {
                    this.LoadIdField = value;
                    this.RaisePropertyChanged("LoadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadMT940Response", Namespace="http://www.gulffinance.com.sa/frs/v1/bank/mt940/operations/load/response")]
    [System.SerializableAttribute()]
    public partial class LoadMT940Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long CodeField;
        
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gulffinance.com.sa/frs/v1/bank/mt940/operations", ConfigurationName="FrsBankMT940Loader.BankMT940Loader")]
    public interface BankMT940Loader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gulffinance.com.sa/frs/v1/bank/mt940/operations/BankMT940Loader/LoadMT" +
            "940", ReplyAction="http://www.gulffinance.com.sa/frs/v1/bank/mt940/operations/BankMT940Loader/LoadMT" +
            "940Response")]
        FRS.WebApi.FrsBankMT940Loader.LoadMT940Response LoadMT940(FRS.WebApi.FrsBankMT940Loader.LoadMT940Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gulffinance.com.sa/frs/v1/bank/mt940/operations/BankMT940Loader/LoadMT" +
            "940", ReplyAction="http://www.gulffinance.com.sa/frs/v1/bank/mt940/operations/BankMT940Loader/LoadMT" +
            "940Response")]
        System.Threading.Tasks.Task<FRS.WebApi.FrsBankMT940Loader.LoadMT940Response> LoadMT940Async(FRS.WebApi.FrsBankMT940Loader.LoadMT940Request request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BankMT940LoaderChannel : FRS.WebApi.FrsBankMT940Loader.BankMT940Loader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankMT940LoaderClient : System.ServiceModel.ClientBase<FRS.WebApi.FrsBankMT940Loader.BankMT940Loader>, FRS.WebApi.FrsBankMT940Loader.BankMT940Loader {
        
        public BankMT940LoaderClient() {
        }
        
        public BankMT940LoaderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankMT940LoaderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankMT940LoaderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankMT940LoaderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FRS.WebApi.FrsBankMT940Loader.LoadMT940Response LoadMT940(FRS.WebApi.FrsBankMT940Loader.LoadMT940Request request) {
            return base.Channel.LoadMT940(request);
        }
        
        public System.Threading.Tasks.Task<FRS.WebApi.FrsBankMT940Loader.LoadMT940Response> LoadMT940Async(FRS.WebApi.FrsBankMT940Loader.LoadMT940Request request) {
            return base.Channel.LoadMT940Async(request);
        }
    }
}
