//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRS.MT940Loader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FRSMT940LoaderContext : DbContext
    {
        public FRSMT940LoaderContext()
            : base("name=FRSMT940LoaderContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FileContent> FileContents { get; set; }
        public virtual DbSet<Load> Loads { get; set; }
        public virtual DbSet<LoadMetaData> LoadMetaDatas { get; set; }
        public virtual DbSet<LoadType> LoadTypes { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MT940Balance> MT940Balance { get; set; }
        public virtual DbSet<MT940CustomerStatement> MT940CustomerStatement { get; set; }
        public virtual DbSet<MT940CustomerStatementTransaction> MT940CustomerStatementTransaction { get; set; }
        public virtual DbSet<MT940Load> MT940Load { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
