//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRS.MT940Loader
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.MenuRights = new HashSet<MenuRight>();
            this.Menu1 = new HashSet<Menu>();
        }
    
        public int MenuId { get; set; }
        public int MenuKey { get; set; }
        public string MenuTitle { get; set; }
        public int SortOrder { get; set; }
        public string MenuTargetController { get; set; }
        public string MenuImagePath { get; set; }
        public string MenuFunction { get; set; }
        public string PermissionKey { get; set; }
        public bool IsRootItem { get; set; }
        public Nullable<int> ParentItem_MenuId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuRight> MenuRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu1 { get; set; }
        public virtual Menu Menu2 { get; set; }
    }
}
