//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRS.MT940Loader
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT940Balance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MT940Balance()
        {
            this.ClosingAvailableBalance = new HashSet<MT940CustomerStatement>();
            this.ClosingBalance = new HashSet<MT940CustomerStatement>();
            this.ForwardAvailableBalance = new HashSet<MT940CustomerStatement>();
            this.OpeningBalance = new HashSet<MT940CustomerStatement>();
        }
    
        public long MT940BalanceId { get; set; }
        public byte CurrencyId { get; set; }
        public string DebitOrCredit { get; set; }
        public System.DateTime EntryDate { get; set; }
        public decimal Value { get; set; }
    
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MT940CustomerStatement> ClosingAvailableBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MT940CustomerStatement> ClosingBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MT940CustomerStatement> ForwardAvailableBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MT940CustomerStatement> OpeningBalance { get; set; }
    }
}
