//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRS.MT940Loader
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT940Balance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MT940Balance()
        {
            this.MT940CustomerStatement = new HashSet<MT940CustomerStatement>();
            this.MT940CustomerStatement1 = new HashSet<MT940CustomerStatement>();
            this.MT940CustomerStatement2 = new HashSet<MT940CustomerStatement>();
            this.MT940CustomerStatement3 = new HashSet<MT940CustomerStatement>();
        }
    
        public long MT940BalanceId { get; set; }
        public byte CurrencyId { get; set; }
        public string DebitOrCredit { get; set; }
        public System.DateTime EntryDate { get; set; }
        public decimal Value { get; set; }
    
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MT940CustomerStatement> MT940CustomerStatement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MT940CustomerStatement> MT940CustomerStatement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MT940CustomerStatement> MT940CustomerStatement2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MT940CustomerStatement> MT940CustomerStatement3 { get; set; }
    }
}
