//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRS.MT940Loader
{
    using System;
    using System.Collections.Generic;
    
    public partial class MT940CustomerStatementTransaction
    {
        public long MT940CustomerStatementTransactionId { get; set; }
        public long MT940CustomerStatementId { get; set; }
        public byte Sequence { get; set; }
        public bool ReadOnly { get; set; }
        public decimal Amount { get; set; }
        public string DebitOrCredit { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string FundsCode { get; set; }
        public string Reference { get; set; }
        public string TransactionType { get; set; }
        public string Value { get; set; }
        public System.DateTime ValueDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual MT940CustomerStatement MT940CustomerStatement { get; set; }
    }
}
